### ISSUE TITLE
Update PyPI version

### ISSUE THREAD

**Issue by themiurgo** [mapado/haversine#2]
It's a pity that the version on PyPI is outdated, especially with regards to speed optimization (C code).

**Comment by jdeniau** [comment]
Ping @brouberol if you know what to do :)

**Comment by themiurgo** [comment]
Not much to do, the version on PyPI is not the latest version available here on GitHub. It's enough to update the PyPI version with the most recent commits. :)

**Comment by erjiang** [comment]
It seems that calling c_haversine is no faster than calling py_haversine. Maybe I am doing something wrong? I installed it using `python setup.py install` in a virtualenv.

**Comment by jdeniau** [comment]
We are looking for getting our PyPI access back from our developer. 
As soon as it's done, we will update the package on PyPI.
It should be done in a few days max.

**Comment by brouberol** [comment]
Sorry about the delay folks, the notification got kinda lost in the mix.
@erjiang you're probably right, the C code is not much faster that the pure Python code, as all the math cuntions

**Comment by jdeniau** [comment]
The version is updated: https://pypi.python.org/pypi/haversine/0.3
