### ISSUE TITLE
Pycharm report error "Import Unit fails" 

### ISSUE THREAD

**Issue by SumitKrGhosh** [mapado/haversine#33]
```
from haversine import haversine, Unit
```
I have installed `haversine` 2.2.0 on python 3.7
I am able to get the  `haversine` function but not the Units.

**Comment by jdeniau** [comment]
I tried to reproduce but no problem for me:

```sh
pipenv --python=3.7
pipenv shell
pip install haversine # install 2.2.0
python --version
# 3.7.3

from haversine import haversine, Unit
print(Unit.KILOMETERS)
<Unit.KILOMETERS: 'km'>
```

Can you try to reproduce this ? 
If it does not work, can you produce a reproductible case ?

**Comment by SumitKrGhosh** [comment]
I see is I installed it as below. Looks like the issue is with the editor PyCharm. this is working fine in the terminal.
`python3 -m pip install haversine`
![image](https://user-images.githubusercontent.com/13426611/87056114-075f8600-c1ba-11ea-8570-258ce92eeb39.png)

**Comment by jdeniau** [comment]
OK. I don't know pycharm. If you find the solution, feel free to open a PR

**Comment by voglster** [comment]
I am using haversine 2.2.0 and PyCharm and importing Unit just fine (python 3.8.3).  If i had a guess this is an install/setup issue on sumit's side of pycharm/venv etc.
  
@SumitKrGhosh do you have PyCharm pointing at the same virtual env you are pip installing to?

**Comment by CrapsJeroen** [comment]
I think the [PyCharm Documentation](https://www.jetbrains.com/help/pycharm/creating-virtual-environment.html#existing-environment) is clear enough @jdeniau and this issue can be closed.
