### ISSUE TITLE
What does Unit.DEGREE option return in haversine function?

### ISSUE THREAD

**Issue by adsk2050** [mapado/haversine#45]
Does it return the angle one has to turn to in order to reach to the destination? Or is it returning the spherical angle subtended by the arc formed by the two points?

e.g.
![image](https://user-images.githubusercontent.com/22856053/171837491-a71e77a7-4dd4-470c-b2dc-0628e24ae3f5.png)
What is it measuring, A or B?

**Comment by jdeniau** [comment]
According to [this test](https://github.com/mapado/haversine/blob/fc1772f0061dee7c1d9059955eed64a693af6bea/tests/test_haversine.py#L31-L37), and [this comment](https://github.com/mapado/haversine/issues/31#issuecomment-617600962) it looks like this is solution B (and I think that should be it).
But I might be mistaken.

Maybe @MuellerSeb or @merschformann can confirm my response ?

**Comment by MuellerSeb** [comment]
The haversine functions returns the [great circle distance](https://en.wikipedia.org/wiki/Great-circle_distance) between two points on a sphere. So B is right.

Notes:
1. on a unit-sphere the angular distance in radians equals the distance between the two points on the sphere (definition of radians)
2. When using "degree", this angle is just converted from radians to degrees

Hope this helps! Cheers

**Comment by merschformann** [comment]
@MuellerSeb beat me to it.

Agree with above. Maybe the following example helps understanding it a bit better too:

```python
>>> import haversine
>>> p1, p2 = (0, -45), (0, 45)
>>> haversine.haversine(p1, p2, haversine.Unit("deg"))
89.99999999999997
```

(except for small numerical issues, we get the 90° difference as expected between -45° & 45°)

**Comment by jdeniau** [comment]
Wow thank you for such quick replies ! 

I added @merschformann test in the test stack and @MuellerSeb explaination in the README in #46
