### ISSUE TITLE
Examples on README.md are incorrect

### ISSUE THREAD

**Issue by uri-rodberg** [mapado/haversine#50]
Hi,

It's written on README.md:
```python
paris = (48.8567, 2.3508) # (lat, lon)
# Finding 32 km west of Paris
inverse_haversine(paris, 32, Direction.WEST)
# returns tuple (49.1444, 2.3508)
```

I ran the code:
```python
paris = (48.8567, 2.3508) # (lat, lon)
print(inverse_haversine(paris, 32, Direction.WEST))
```
And I received `(48.85587279023947, 1.9134085092836945)`. Also, notice that the latitude is not exactly `48.8567` as I expected, but it's different than `(49.1444, 2.3508)` in the README.md.

I didn't check all the examples.

**Comment by CrapsJeroen** [comment]
Hi @uri-rodberg 

You're absolutely right that the first two examples concerning the inverser_haversine function in the readme are wrong.
